#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-gpu=12
#SBATCH --time=8:00:00
#SBATCH --job-name=save_cats
#SBATCH -p gpu
#SBATCH --mem=256G
#SBATCH --gpus-per-node=1
#SBATCH --output=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.out
#SBATCH --error=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.err

module purge
module load python
module load cuda
module load cudnn
module load nccl
source ~/miniconda3/bin/activate ili-sbi

cd /mnt/home/spandey/ceph/CHARM/charm/


srun --time=1 python predict_save_halo_cats.py 1400
srun --time=1 python predict_save_halo_cats.py 1401
srun --time=1 python predict_save_halo_cats.py 1402
srun --time=1 python predict_save_halo_cats.py 1403
srun --time=1 python predict_save_halo_cats.py 1404
srun --time=1 python predict_save_halo_cats.py 1405
srun --time=1 python predict_save_halo_cats.py 1406
srun --time=1 python predict_save_halo_cats.py 1407
srun --time=1 python predict_save_halo_cats.py 1408
srun --time=1 python predict_save_halo_cats.py 1409
srun --time=1 python predict_save_halo_cats.py 1410
srun --time=1 python predict_save_halo_cats.py 1411
srun --time=1 python predict_save_halo_cats.py 1412
srun --time=1 python predict_save_halo_cats.py 1413
srun --time=1 python predict_save_halo_cats.py 1414
srun --time=1 python predict_save_halo_cats.py 1415
srun --time=1 python predict_save_halo_cats.py 1416
srun --time=1 python predict_save_halo_cats.py 1417
srun --time=1 python predict_save_halo_cats.py 1418
srun --time=1 python predict_save_halo_cats.py 1419
srun --time=1 python predict_save_halo_cats.py 1420
srun --time=1 python predict_save_halo_cats.py 1421
srun --time=1 python predict_save_halo_cats.py 1422
srun --time=1 python predict_save_halo_cats.py 1423
srun --time=1 python predict_save_halo_cats.py 1424
srun --time=1 python predict_save_halo_cats.py 1425
srun --time=1 python predict_save_halo_cats.py 1426
srun --time=1 python predict_save_halo_cats.py 1427
srun --time=1 python predict_save_halo_cats.py 1428
srun --time=1 python predict_save_halo_cats.py 1429
srun --time=1 python predict_save_halo_cats.py 1430
srun --time=1 python predict_save_halo_cats.py 1431
srun --time=1 python predict_save_halo_cats.py 1432
srun --time=1 python predict_save_halo_cats.py 1433
srun --time=1 python predict_save_halo_cats.py 1434
srun --time=1 python predict_save_halo_cats.py 1435
srun --time=1 python predict_save_halo_cats.py 1436
srun --time=1 python predict_save_halo_cats.py 1437
srun --time=1 python predict_save_halo_cats.py 1438
srun --time=1 python predict_save_halo_cats.py 1439
srun --time=1 python predict_save_halo_cats.py 1440
srun --time=1 python predict_save_halo_cats.py 1441
srun --time=1 python predict_save_halo_cats.py 1442
srun --time=1 python predict_save_halo_cats.py 1443
srun --time=1 python predict_save_halo_cats.py 1444
srun --time=1 python predict_save_halo_cats.py 1445
srun --time=1 python predict_save_halo_cats.py 1446
srun --time=1 python predict_save_halo_cats.py 1447
srun --time=1 python predict_save_halo_cats.py 1448
srun --time=1 python predict_save_halo_cats.py 1449
srun --time=1 python predict_save_halo_cats.py 1450
srun --time=1 python predict_save_halo_cats.py 1451
srun --time=1 python predict_save_halo_cats.py 1452
srun --time=1 python predict_save_halo_cats.py 1453
srun --time=1 python predict_save_halo_cats.py 1454
srun --time=1 python predict_save_halo_cats.py 1455
srun --time=1 python predict_save_halo_cats.py 1456
srun --time=1 python predict_save_halo_cats.py 1457
srun --time=1 python predict_save_halo_cats.py 1458
srun --time=1 python predict_save_halo_cats.py 1459
srun --time=1 python predict_save_halo_cats.py 1460
srun --time=1 python predict_save_halo_cats.py 1461
srun --time=1 python predict_save_halo_cats.py 1462
srun --time=1 python predict_save_halo_cats.py 1463
srun --time=1 python predict_save_halo_cats.py 1464
srun --time=1 python predict_save_halo_cats.py 1465
srun --time=1 python predict_save_halo_cats.py 1466
srun --time=1 python predict_save_halo_cats.py 1467
srun --time=1 python predict_save_halo_cats.py 1468
srun --time=1 python predict_save_halo_cats.py 1469
srun --time=1 python predict_save_halo_cats.py 1470
srun --time=1 python predict_save_halo_cats.py 1471
srun --time=1 python predict_save_halo_cats.py 1472
srun --time=1 python predict_save_halo_cats.py 1473
srun --time=1 python predict_save_halo_cats.py 1474
srun --time=1 python predict_save_halo_cats.py 1475
srun --time=1 python predict_save_halo_cats.py 1476
srun --time=1 python predict_save_halo_cats.py 1477
srun --time=1 python predict_save_halo_cats.py 1478
srun --time=1 python predict_save_halo_cats.py 1479
srun --time=1 python predict_save_halo_cats.py 1480
srun --time=1 python predict_save_halo_cats.py 1481
srun --time=1 python predict_save_halo_cats.py 1482
srun --time=1 python predict_save_halo_cats.py 1483
srun --time=1 python predict_save_halo_cats.py 1484
srun --time=1 python predict_save_halo_cats.py 1485
srun --time=1 python predict_save_halo_cats.py 1486
srun --time=1 python predict_save_halo_cats.py 1487
srun --time=1 python predict_save_halo_cats.py 1488
srun --time=1 python predict_save_halo_cats.py 1489
srun --time=1 python predict_save_halo_cats.py 1490
srun --time=1 python predict_save_halo_cats.py 1491
srun --time=1 python predict_save_halo_cats.py 1492
srun --time=1 python predict_save_halo_cats.py 1493
srun --time=1 python predict_save_halo_cats.py 1494
srun --time=1 python predict_save_halo_cats.py 1495
srun --time=1 python predict_save_halo_cats.py 1496
srun --time=1 python predict_save_halo_cats.py 1497
srun --time=1 python predict_save_halo_cats.py 1498
srun --time=1 python predict_save_halo_cats.py 1499
srun --time=1 python predict_save_halo_cats.py 1500
srun --time=1 python predict_save_halo_cats.py 1501
srun --time=1 python predict_save_halo_cats.py 1502
srun --time=1 python predict_save_halo_cats.py 1503
srun --time=1 python predict_save_halo_cats.py 1504
srun --time=1 python predict_save_halo_cats.py 1505
srun --time=1 python predict_save_halo_cats.py 1506
srun --time=1 python predict_save_halo_cats.py 1507
srun --time=1 python predict_save_halo_cats.py 1508
srun --time=1 python predict_save_halo_cats.py 1509
srun --time=1 python predict_save_halo_cats.py 1510
srun --time=1 python predict_save_halo_cats.py 1511
srun --time=1 python predict_save_halo_cats.py 1512
srun --time=1 python predict_save_halo_cats.py 1513
srun --time=1 python predict_save_halo_cats.py 1514
srun --time=1 python predict_save_halo_cats.py 1515
srun --time=1 python predict_save_halo_cats.py 1516
srun --time=1 python predict_save_halo_cats.py 1517
srun --time=1 python predict_save_halo_cats.py 1518
srun --time=1 python predict_save_halo_cats.py 1519
srun --time=1 python predict_save_halo_cats.py 1520
srun --time=1 python predict_save_halo_cats.py 1521
srun --time=1 python predict_save_halo_cats.py 1522
srun --time=1 python predict_save_halo_cats.py 1523
srun --time=1 python predict_save_halo_cats.py 1524
srun --time=1 python predict_save_halo_cats.py 1525
srun --time=1 python predict_save_halo_cats.py 1526
srun --time=1 python predict_save_halo_cats.py 1527
srun --time=1 python predict_save_halo_cats.py 1528
srun --time=1 python predict_save_halo_cats.py 1529
srun --time=1 python predict_save_halo_cats.py 1530
srun --time=1 python predict_save_halo_cats.py 1531
srun --time=1 python predict_save_halo_cats.py 1532
srun --time=1 python predict_save_halo_cats.py 1533
srun --time=1 python predict_save_halo_cats.py 1534
srun --time=1 python predict_save_halo_cats.py 1535
srun --time=1 python predict_save_halo_cats.py 1536
srun --time=1 python predict_save_halo_cats.py 1537
srun --time=1 python predict_save_halo_cats.py 1538
srun --time=1 python predict_save_halo_cats.py 1539
srun --time=1 python predict_save_halo_cats.py 1540
srun --time=1 python predict_save_halo_cats.py 1541
srun --time=1 python predict_save_halo_cats.py 1542
srun --time=1 python predict_save_halo_cats.py 1543
srun --time=1 python predict_save_halo_cats.py 1544
srun --time=1 python predict_save_halo_cats.py 1545
srun --time=1 python predict_save_halo_cats.py 1546
srun --time=1 python predict_save_halo_cats.py 1547
srun --time=1 python predict_save_halo_cats.py 1548
srun --time=1 python predict_save_halo_cats.py 1549
srun --time=1 python predict_save_halo_cats.py 1550
srun --time=1 python predict_save_halo_cats.py 1551
srun --time=1 python predict_save_halo_cats.py 1552
srun --time=1 python predict_save_halo_cats.py 1553
srun --time=1 python predict_save_halo_cats.py 1554
srun --time=1 python predict_save_halo_cats.py 1555
srun --time=1 python predict_save_halo_cats.py 1556
srun --time=1 python predict_save_halo_cats.py 1557
srun --time=1 python predict_save_halo_cats.py 1558
srun --time=1 python predict_save_halo_cats.py 1559
srun --time=1 python predict_save_halo_cats.py 1560
srun --time=1 python predict_save_halo_cats.py 1561
srun --time=1 python predict_save_halo_cats.py 1562
srun --time=1 python predict_save_halo_cats.py 1563
srun --time=1 python predict_save_halo_cats.py 1564
srun --time=1 python predict_save_halo_cats.py 1565
srun --time=1 python predict_save_halo_cats.py 1566
srun --time=1 python predict_save_halo_cats.py 1567
srun --time=1 python predict_save_halo_cats.py 1568
srun --time=1 python predict_save_halo_cats.py 1569
srun --time=1 python predict_save_halo_cats.py 1570
srun --time=1 python predict_save_halo_cats.py 1571
srun --time=1 python predict_save_halo_cats.py 1572
srun --time=1 python predict_save_halo_cats.py 1573
srun --time=1 python predict_save_halo_cats.py 1574
srun --time=1 python predict_save_halo_cats.py 1575
srun --time=1 python predict_save_halo_cats.py 1576
srun --time=1 python predict_save_halo_cats.py 1577
srun --time=1 python predict_save_halo_cats.py 1578
srun --time=1 python predict_save_halo_cats.py 1579
srun --time=1 python predict_save_halo_cats.py 1580
srun --time=1 python predict_save_halo_cats.py 1581
srun --time=1 python predict_save_halo_cats.py 1582
srun --time=1 python predict_save_halo_cats.py 1583
srun --time=1 python predict_save_halo_cats.py 1584
srun --time=1 python predict_save_halo_cats.py 1585
srun --time=1 python predict_save_halo_cats.py 1586
srun --time=1 python predict_save_halo_cats.py 1587
srun --time=1 python predict_save_halo_cats.py 1588
srun --time=1 python predict_save_halo_cats.py 1589
srun --time=1 python predict_save_halo_cats.py 1590
srun --time=1 python predict_save_halo_cats.py 1591
srun --time=1 python predict_save_halo_cats.py 1592
srun --time=1 python predict_save_halo_cats.py 1593
srun --time=1 python predict_save_halo_cats.py 1594
srun --time=1 python predict_save_halo_cats.py 1595
srun --time=1 python predict_save_halo_cats.py 1596
srun --time=1 python predict_save_halo_cats.py 1597
srun --time=1 python predict_save_halo_cats.py 1598
srun --time=1 python predict_save_halo_cats.py 1599


echo "All done!"
