#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-gpu=12
#SBATCH --time=8:00:00
#SBATCH --job-name=save_cats
#SBATCH -p gpu
#SBATCH --mem=256G
#SBATCH --gpus-per-node=1
#SBATCH --output=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.out
#SBATCH --error=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.err

module purge
module load python
module load cuda
module load cudnn
module load nccl
source ~/miniconda3/bin/activate ili-sbi

cd /mnt/home/spandey/ceph/CHARM/charm/


srun --time=1 python predict_save_halo_cats.py 800
srun --time=1 python predict_save_halo_cats.py 801
srun --time=1 python predict_save_halo_cats.py 802
srun --time=1 python predict_save_halo_cats.py 803
srun --time=1 python predict_save_halo_cats.py 804
srun --time=1 python predict_save_halo_cats.py 805
srun --time=1 python predict_save_halo_cats.py 806
srun --time=1 python predict_save_halo_cats.py 807
srun --time=1 python predict_save_halo_cats.py 808
srun --time=1 python predict_save_halo_cats.py 809
srun --time=1 python predict_save_halo_cats.py 810
srun --time=1 python predict_save_halo_cats.py 811
srun --time=1 python predict_save_halo_cats.py 812
srun --time=1 python predict_save_halo_cats.py 813
srun --time=1 python predict_save_halo_cats.py 814
srun --time=1 python predict_save_halo_cats.py 815
srun --time=1 python predict_save_halo_cats.py 816
srun --time=1 python predict_save_halo_cats.py 817
srun --time=1 python predict_save_halo_cats.py 818
srun --time=1 python predict_save_halo_cats.py 819
srun --time=1 python predict_save_halo_cats.py 820
srun --time=1 python predict_save_halo_cats.py 821
srun --time=1 python predict_save_halo_cats.py 822
srun --time=1 python predict_save_halo_cats.py 823
srun --time=1 python predict_save_halo_cats.py 824
srun --time=1 python predict_save_halo_cats.py 825
srun --time=1 python predict_save_halo_cats.py 826
srun --time=1 python predict_save_halo_cats.py 827
srun --time=1 python predict_save_halo_cats.py 828
srun --time=1 python predict_save_halo_cats.py 829
srun --time=1 python predict_save_halo_cats.py 830
srun --time=1 python predict_save_halo_cats.py 831
srun --time=1 python predict_save_halo_cats.py 832
srun --time=1 python predict_save_halo_cats.py 833
srun --time=1 python predict_save_halo_cats.py 834
srun --time=1 python predict_save_halo_cats.py 835
srun --time=1 python predict_save_halo_cats.py 836
srun --time=1 python predict_save_halo_cats.py 837
srun --time=1 python predict_save_halo_cats.py 838
srun --time=1 python predict_save_halo_cats.py 839
srun --time=1 python predict_save_halo_cats.py 840
srun --time=1 python predict_save_halo_cats.py 841
srun --time=1 python predict_save_halo_cats.py 842
srun --time=1 python predict_save_halo_cats.py 843
srun --time=1 python predict_save_halo_cats.py 844
srun --time=1 python predict_save_halo_cats.py 845
srun --time=1 python predict_save_halo_cats.py 846
srun --time=1 python predict_save_halo_cats.py 847
srun --time=1 python predict_save_halo_cats.py 848
srun --time=1 python predict_save_halo_cats.py 849
srun --time=1 python predict_save_halo_cats.py 850
srun --time=1 python predict_save_halo_cats.py 851
srun --time=1 python predict_save_halo_cats.py 852
srun --time=1 python predict_save_halo_cats.py 853
srun --time=1 python predict_save_halo_cats.py 854
srun --time=1 python predict_save_halo_cats.py 855
srun --time=1 python predict_save_halo_cats.py 856
srun --time=1 python predict_save_halo_cats.py 857
srun --time=1 python predict_save_halo_cats.py 858
srun --time=1 python predict_save_halo_cats.py 859
srun --time=1 python predict_save_halo_cats.py 860
srun --time=1 python predict_save_halo_cats.py 861
srun --time=1 python predict_save_halo_cats.py 862
srun --time=1 python predict_save_halo_cats.py 863
srun --time=1 python predict_save_halo_cats.py 864
srun --time=1 python predict_save_halo_cats.py 865
srun --time=1 python predict_save_halo_cats.py 866
srun --time=1 python predict_save_halo_cats.py 867
srun --time=1 python predict_save_halo_cats.py 868
srun --time=1 python predict_save_halo_cats.py 869
srun --time=1 python predict_save_halo_cats.py 870
srun --time=1 python predict_save_halo_cats.py 871
srun --time=1 python predict_save_halo_cats.py 872
srun --time=1 python predict_save_halo_cats.py 873
srun --time=1 python predict_save_halo_cats.py 874
srun --time=1 python predict_save_halo_cats.py 875
srun --time=1 python predict_save_halo_cats.py 876
srun --time=1 python predict_save_halo_cats.py 877
srun --time=1 python predict_save_halo_cats.py 878
srun --time=1 python predict_save_halo_cats.py 879
srun --time=1 python predict_save_halo_cats.py 880
srun --time=1 python predict_save_halo_cats.py 881
srun --time=1 python predict_save_halo_cats.py 882
srun --time=1 python predict_save_halo_cats.py 883
srun --time=1 python predict_save_halo_cats.py 884
srun --time=1 python predict_save_halo_cats.py 885
srun --time=1 python predict_save_halo_cats.py 886
srun --time=1 python predict_save_halo_cats.py 887
srun --time=1 python predict_save_halo_cats.py 888
srun --time=1 python predict_save_halo_cats.py 889
srun --time=1 python predict_save_halo_cats.py 890
srun --time=1 python predict_save_halo_cats.py 891
srun --time=1 python predict_save_halo_cats.py 892
srun --time=1 python predict_save_halo_cats.py 893
srun --time=1 python predict_save_halo_cats.py 894
srun --time=1 python predict_save_halo_cats.py 895
srun --time=1 python predict_save_halo_cats.py 896
srun --time=1 python predict_save_halo_cats.py 897
srun --time=1 python predict_save_halo_cats.py 898
srun --time=1 python predict_save_halo_cats.py 899
srun --time=1 python predict_save_halo_cats.py 900
srun --time=1 python predict_save_halo_cats.py 901
srun --time=1 python predict_save_halo_cats.py 902
srun --time=1 python predict_save_halo_cats.py 903
srun --time=1 python predict_save_halo_cats.py 904
srun --time=1 python predict_save_halo_cats.py 905
srun --time=1 python predict_save_halo_cats.py 906
srun --time=1 python predict_save_halo_cats.py 907
srun --time=1 python predict_save_halo_cats.py 908
srun --time=1 python predict_save_halo_cats.py 909
srun --time=1 python predict_save_halo_cats.py 910
srun --time=1 python predict_save_halo_cats.py 911
srun --time=1 python predict_save_halo_cats.py 912
srun --time=1 python predict_save_halo_cats.py 913
srun --time=1 python predict_save_halo_cats.py 914
srun --time=1 python predict_save_halo_cats.py 915
srun --time=1 python predict_save_halo_cats.py 916
srun --time=1 python predict_save_halo_cats.py 917
srun --time=1 python predict_save_halo_cats.py 918
srun --time=1 python predict_save_halo_cats.py 919
srun --time=1 python predict_save_halo_cats.py 920
srun --time=1 python predict_save_halo_cats.py 921
srun --time=1 python predict_save_halo_cats.py 922
srun --time=1 python predict_save_halo_cats.py 923
srun --time=1 python predict_save_halo_cats.py 924
srun --time=1 python predict_save_halo_cats.py 925
srun --time=1 python predict_save_halo_cats.py 926
srun --time=1 python predict_save_halo_cats.py 927
srun --time=1 python predict_save_halo_cats.py 928
srun --time=1 python predict_save_halo_cats.py 929
srun --time=1 python predict_save_halo_cats.py 930
srun --time=1 python predict_save_halo_cats.py 931
srun --time=1 python predict_save_halo_cats.py 932
srun --time=1 python predict_save_halo_cats.py 933
srun --time=1 python predict_save_halo_cats.py 934
srun --time=1 python predict_save_halo_cats.py 935
srun --time=1 python predict_save_halo_cats.py 936
srun --time=1 python predict_save_halo_cats.py 937
srun --time=1 python predict_save_halo_cats.py 938
srun --time=1 python predict_save_halo_cats.py 939
srun --time=1 python predict_save_halo_cats.py 940
srun --time=1 python predict_save_halo_cats.py 941
srun --time=1 python predict_save_halo_cats.py 942
srun --time=1 python predict_save_halo_cats.py 943
srun --time=1 python predict_save_halo_cats.py 944
srun --time=1 python predict_save_halo_cats.py 945
srun --time=1 python predict_save_halo_cats.py 946
srun --time=1 python predict_save_halo_cats.py 947
srun --time=1 python predict_save_halo_cats.py 948
srun --time=1 python predict_save_halo_cats.py 949
srun --time=1 python predict_save_halo_cats.py 950
srun --time=1 python predict_save_halo_cats.py 951
srun --time=1 python predict_save_halo_cats.py 952
srun --time=1 python predict_save_halo_cats.py 953
srun --time=1 python predict_save_halo_cats.py 954
srun --time=1 python predict_save_halo_cats.py 955
srun --time=1 python predict_save_halo_cats.py 956
srun --time=1 python predict_save_halo_cats.py 957
srun --time=1 python predict_save_halo_cats.py 958
srun --time=1 python predict_save_halo_cats.py 959
srun --time=1 python predict_save_halo_cats.py 960
srun --time=1 python predict_save_halo_cats.py 961
srun --time=1 python predict_save_halo_cats.py 962
srun --time=1 python predict_save_halo_cats.py 963
srun --time=1 python predict_save_halo_cats.py 964
srun --time=1 python predict_save_halo_cats.py 965
srun --time=1 python predict_save_halo_cats.py 966
srun --time=1 python predict_save_halo_cats.py 967
srun --time=1 python predict_save_halo_cats.py 968
srun --time=1 python predict_save_halo_cats.py 969
srun --time=1 python predict_save_halo_cats.py 970
srun --time=1 python predict_save_halo_cats.py 971
srun --time=1 python predict_save_halo_cats.py 972
srun --time=1 python predict_save_halo_cats.py 973
srun --time=1 python predict_save_halo_cats.py 974
srun --time=1 python predict_save_halo_cats.py 975
srun --time=1 python predict_save_halo_cats.py 976
srun --time=1 python predict_save_halo_cats.py 977
srun --time=1 python predict_save_halo_cats.py 978
srun --time=1 python predict_save_halo_cats.py 979
srun --time=1 python predict_save_halo_cats.py 980
srun --time=1 python predict_save_halo_cats.py 981
srun --time=1 python predict_save_halo_cats.py 982
srun --time=1 python predict_save_halo_cats.py 983
srun --time=1 python predict_save_halo_cats.py 984
srun --time=1 python predict_save_halo_cats.py 985
srun --time=1 python predict_save_halo_cats.py 986
srun --time=1 python predict_save_halo_cats.py 987
srun --time=1 python predict_save_halo_cats.py 988
srun --time=1 python predict_save_halo_cats.py 989
srun --time=1 python predict_save_halo_cats.py 990
srun --time=1 python predict_save_halo_cats.py 991
srun --time=1 python predict_save_halo_cats.py 992
srun --time=1 python predict_save_halo_cats.py 993
srun --time=1 python predict_save_halo_cats.py 994
srun --time=1 python predict_save_halo_cats.py 995
srun --time=1 python predict_save_halo_cats.py 996
srun --time=1 python predict_save_halo_cats.py 997
srun --time=1 python predict_save_halo_cats.py 998
srun --time=1 python predict_save_halo_cats.py 999


echo "All done!"
