#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-gpu=12
#SBATCH --time=8:00:00
#SBATCH --job-name=save_cats
#SBATCH -p gpu
#SBATCH --mem=256G
#SBATCH --gpus-per-node=1
#SBATCH --output=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.out
#SBATCH --error=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.err

module purge
module load python
module load cuda
module load cudnn
module load nccl
source ~/miniconda3/bin/activate ili-sbi

cd /mnt/home/spandey/ceph/CHARM/charm/


srun --time=1 python predict_save_halo_cats.py 400
srun --time=1 python predict_save_halo_cats.py 401
srun --time=1 python predict_save_halo_cats.py 402
srun --time=1 python predict_save_halo_cats.py 403
srun --time=1 python predict_save_halo_cats.py 404
srun --time=1 python predict_save_halo_cats.py 405
srun --time=1 python predict_save_halo_cats.py 406
srun --time=1 python predict_save_halo_cats.py 407
srun --time=1 python predict_save_halo_cats.py 408
srun --time=1 python predict_save_halo_cats.py 409
srun --time=1 python predict_save_halo_cats.py 410
srun --time=1 python predict_save_halo_cats.py 411
srun --time=1 python predict_save_halo_cats.py 412
srun --time=1 python predict_save_halo_cats.py 413
srun --time=1 python predict_save_halo_cats.py 414
srun --time=1 python predict_save_halo_cats.py 415
srun --time=1 python predict_save_halo_cats.py 416
srun --time=1 python predict_save_halo_cats.py 417
srun --time=1 python predict_save_halo_cats.py 418
srun --time=1 python predict_save_halo_cats.py 419
srun --time=1 python predict_save_halo_cats.py 420
srun --time=1 python predict_save_halo_cats.py 421
srun --time=1 python predict_save_halo_cats.py 422
srun --time=1 python predict_save_halo_cats.py 423
srun --time=1 python predict_save_halo_cats.py 424
srun --time=1 python predict_save_halo_cats.py 425
srun --time=1 python predict_save_halo_cats.py 426
srun --time=1 python predict_save_halo_cats.py 427
srun --time=1 python predict_save_halo_cats.py 428
srun --time=1 python predict_save_halo_cats.py 429
srun --time=1 python predict_save_halo_cats.py 430
srun --time=1 python predict_save_halo_cats.py 431
srun --time=1 python predict_save_halo_cats.py 432
srun --time=1 python predict_save_halo_cats.py 433
srun --time=1 python predict_save_halo_cats.py 434
srun --time=1 python predict_save_halo_cats.py 435
srun --time=1 python predict_save_halo_cats.py 436
srun --time=1 python predict_save_halo_cats.py 437
srun --time=1 python predict_save_halo_cats.py 438
srun --time=1 python predict_save_halo_cats.py 439
srun --time=1 python predict_save_halo_cats.py 440
srun --time=1 python predict_save_halo_cats.py 441
srun --time=1 python predict_save_halo_cats.py 442
srun --time=1 python predict_save_halo_cats.py 443
srun --time=1 python predict_save_halo_cats.py 444
srun --time=1 python predict_save_halo_cats.py 445
srun --time=1 python predict_save_halo_cats.py 446
srun --time=1 python predict_save_halo_cats.py 447
srun --time=1 python predict_save_halo_cats.py 448
srun --time=1 python predict_save_halo_cats.py 449
srun --time=1 python predict_save_halo_cats.py 450
srun --time=1 python predict_save_halo_cats.py 451
srun --time=1 python predict_save_halo_cats.py 452
srun --time=1 python predict_save_halo_cats.py 453
srun --time=1 python predict_save_halo_cats.py 454
srun --time=1 python predict_save_halo_cats.py 455
srun --time=1 python predict_save_halo_cats.py 456
srun --time=1 python predict_save_halo_cats.py 457
srun --time=1 python predict_save_halo_cats.py 458
srun --time=1 python predict_save_halo_cats.py 459
srun --time=1 python predict_save_halo_cats.py 460
srun --time=1 python predict_save_halo_cats.py 461
srun --time=1 python predict_save_halo_cats.py 462
srun --time=1 python predict_save_halo_cats.py 463
srun --time=1 python predict_save_halo_cats.py 464
srun --time=1 python predict_save_halo_cats.py 465
srun --time=1 python predict_save_halo_cats.py 466
srun --time=1 python predict_save_halo_cats.py 467
srun --time=1 python predict_save_halo_cats.py 468
srun --time=1 python predict_save_halo_cats.py 469
srun --time=1 python predict_save_halo_cats.py 470
srun --time=1 python predict_save_halo_cats.py 471
srun --time=1 python predict_save_halo_cats.py 472
srun --time=1 python predict_save_halo_cats.py 473
srun --time=1 python predict_save_halo_cats.py 474
srun --time=1 python predict_save_halo_cats.py 475
srun --time=1 python predict_save_halo_cats.py 476
srun --time=1 python predict_save_halo_cats.py 477
srun --time=1 python predict_save_halo_cats.py 478
srun --time=1 python predict_save_halo_cats.py 479
srun --time=1 python predict_save_halo_cats.py 480
srun --time=1 python predict_save_halo_cats.py 481
srun --time=1 python predict_save_halo_cats.py 482
srun --time=1 python predict_save_halo_cats.py 483
srun --time=1 python predict_save_halo_cats.py 484
srun --time=1 python predict_save_halo_cats.py 485
srun --time=1 python predict_save_halo_cats.py 486
srun --time=1 python predict_save_halo_cats.py 487
srun --time=1 python predict_save_halo_cats.py 488
srun --time=1 python predict_save_halo_cats.py 489
srun --time=1 python predict_save_halo_cats.py 490
srun --time=1 python predict_save_halo_cats.py 491
srun --time=1 python predict_save_halo_cats.py 492
srun --time=1 python predict_save_halo_cats.py 493
srun --time=1 python predict_save_halo_cats.py 494
srun --time=1 python predict_save_halo_cats.py 495
srun --time=1 python predict_save_halo_cats.py 496
srun --time=1 python predict_save_halo_cats.py 497
srun --time=1 python predict_save_halo_cats.py 498
srun --time=1 python predict_save_halo_cats.py 499
srun --time=1 python predict_save_halo_cats.py 500
srun --time=1 python predict_save_halo_cats.py 501
srun --time=1 python predict_save_halo_cats.py 502
srun --time=1 python predict_save_halo_cats.py 503
srun --time=1 python predict_save_halo_cats.py 504
srun --time=1 python predict_save_halo_cats.py 505
srun --time=1 python predict_save_halo_cats.py 506
srun --time=1 python predict_save_halo_cats.py 507
srun --time=1 python predict_save_halo_cats.py 508
srun --time=1 python predict_save_halo_cats.py 509
srun --time=1 python predict_save_halo_cats.py 510
srun --time=1 python predict_save_halo_cats.py 511
srun --time=1 python predict_save_halo_cats.py 512
srun --time=1 python predict_save_halo_cats.py 513
srun --time=1 python predict_save_halo_cats.py 514
srun --time=1 python predict_save_halo_cats.py 515
srun --time=1 python predict_save_halo_cats.py 516
srun --time=1 python predict_save_halo_cats.py 517
srun --time=1 python predict_save_halo_cats.py 518
srun --time=1 python predict_save_halo_cats.py 519
srun --time=1 python predict_save_halo_cats.py 520
srun --time=1 python predict_save_halo_cats.py 521
srun --time=1 python predict_save_halo_cats.py 522
srun --time=1 python predict_save_halo_cats.py 523
srun --time=1 python predict_save_halo_cats.py 524
srun --time=1 python predict_save_halo_cats.py 525
srun --time=1 python predict_save_halo_cats.py 526
srun --time=1 python predict_save_halo_cats.py 527
srun --time=1 python predict_save_halo_cats.py 528
srun --time=1 python predict_save_halo_cats.py 529
srun --time=1 python predict_save_halo_cats.py 530
srun --time=1 python predict_save_halo_cats.py 531
srun --time=1 python predict_save_halo_cats.py 532
srun --time=1 python predict_save_halo_cats.py 533
srun --time=1 python predict_save_halo_cats.py 534
srun --time=1 python predict_save_halo_cats.py 535
srun --time=1 python predict_save_halo_cats.py 536
srun --time=1 python predict_save_halo_cats.py 537
srun --time=1 python predict_save_halo_cats.py 538
srun --time=1 python predict_save_halo_cats.py 539
srun --time=1 python predict_save_halo_cats.py 540
srun --time=1 python predict_save_halo_cats.py 541
srun --time=1 python predict_save_halo_cats.py 542
srun --time=1 python predict_save_halo_cats.py 543
srun --time=1 python predict_save_halo_cats.py 544
srun --time=1 python predict_save_halo_cats.py 545
srun --time=1 python predict_save_halo_cats.py 546
srun --time=1 python predict_save_halo_cats.py 547
srun --time=1 python predict_save_halo_cats.py 548
srun --time=1 python predict_save_halo_cats.py 549
srun --time=1 python predict_save_halo_cats.py 550
srun --time=1 python predict_save_halo_cats.py 551
srun --time=1 python predict_save_halo_cats.py 552
srun --time=1 python predict_save_halo_cats.py 553
srun --time=1 python predict_save_halo_cats.py 554
srun --time=1 python predict_save_halo_cats.py 555
srun --time=1 python predict_save_halo_cats.py 556
srun --time=1 python predict_save_halo_cats.py 557
srun --time=1 python predict_save_halo_cats.py 558
srun --time=1 python predict_save_halo_cats.py 559
srun --time=1 python predict_save_halo_cats.py 560
srun --time=1 python predict_save_halo_cats.py 561
srun --time=1 python predict_save_halo_cats.py 562
srun --time=1 python predict_save_halo_cats.py 563
srun --time=1 python predict_save_halo_cats.py 564
srun --time=1 python predict_save_halo_cats.py 565
srun --time=1 python predict_save_halo_cats.py 566
srun --time=1 python predict_save_halo_cats.py 567
srun --time=1 python predict_save_halo_cats.py 568
srun --time=1 python predict_save_halo_cats.py 569
srun --time=1 python predict_save_halo_cats.py 570
srun --time=1 python predict_save_halo_cats.py 571
srun --time=1 python predict_save_halo_cats.py 572
srun --time=1 python predict_save_halo_cats.py 573
srun --time=1 python predict_save_halo_cats.py 574
srun --time=1 python predict_save_halo_cats.py 575
srun --time=1 python predict_save_halo_cats.py 576
srun --time=1 python predict_save_halo_cats.py 577
srun --time=1 python predict_save_halo_cats.py 578
srun --time=1 python predict_save_halo_cats.py 579
srun --time=1 python predict_save_halo_cats.py 580
srun --time=1 python predict_save_halo_cats.py 581
srun --time=1 python predict_save_halo_cats.py 582
srun --time=1 python predict_save_halo_cats.py 583
srun --time=1 python predict_save_halo_cats.py 584
srun --time=1 python predict_save_halo_cats.py 585
srun --time=1 python predict_save_halo_cats.py 586
srun --time=1 python predict_save_halo_cats.py 587
srun --time=1 python predict_save_halo_cats.py 588
srun --time=1 python predict_save_halo_cats.py 589
srun --time=1 python predict_save_halo_cats.py 590
srun --time=1 python predict_save_halo_cats.py 591
srun --time=1 python predict_save_halo_cats.py 592
srun --time=1 python predict_save_halo_cats.py 593
srun --time=1 python predict_save_halo_cats.py 594
srun --time=1 python predict_save_halo_cats.py 595
srun --time=1 python predict_save_halo_cats.py 596
srun --time=1 python predict_save_halo_cats.py 597
srun --time=1 python predict_save_halo_cats.py 598
srun --time=1 python predict_save_halo_cats.py 599


echo "All done!"
