#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-gpu=12
#SBATCH --time=8:00:00
#SBATCH --job-name=save_cats
#SBATCH -p gpu
#SBATCH --mem=256G
#SBATCH --gpus-per-node=1
#SBATCH --output=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.out
#SBATCH --error=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.err

module purge
module load python
module load cuda
module load cudnn
module load nccl
source ~/miniconda3/bin/activate ili-sbi

cd /mnt/home/spandey/ceph/CHARM/charm/


srun --time=1 python predict_save_halo_cats.py 0
srun --time=1 python predict_save_halo_cats.py 1
srun --time=1 python predict_save_halo_cats.py 2
srun --time=1 python predict_save_halo_cats.py 3
srun --time=1 python predict_save_halo_cats.py 4
srun --time=1 python predict_save_halo_cats.py 5
srun --time=1 python predict_save_halo_cats.py 6
srun --time=1 python predict_save_halo_cats.py 7
srun --time=1 python predict_save_halo_cats.py 8
srun --time=1 python predict_save_halo_cats.py 9
srun --time=1 python predict_save_halo_cats.py 10
srun --time=1 python predict_save_halo_cats.py 11
srun --time=1 python predict_save_halo_cats.py 12
srun --time=1 python predict_save_halo_cats.py 13
srun --time=1 python predict_save_halo_cats.py 14
srun --time=1 python predict_save_halo_cats.py 15
srun --time=1 python predict_save_halo_cats.py 16
srun --time=1 python predict_save_halo_cats.py 17
srun --time=1 python predict_save_halo_cats.py 18
srun --time=1 python predict_save_halo_cats.py 19
srun --time=1 python predict_save_halo_cats.py 20
srun --time=1 python predict_save_halo_cats.py 21
srun --time=1 python predict_save_halo_cats.py 22
srun --time=1 python predict_save_halo_cats.py 23
srun --time=1 python predict_save_halo_cats.py 24
srun --time=1 python predict_save_halo_cats.py 25
srun --time=1 python predict_save_halo_cats.py 26
srun --time=1 python predict_save_halo_cats.py 27
srun --time=1 python predict_save_halo_cats.py 28
srun --time=1 python predict_save_halo_cats.py 29
srun --time=1 python predict_save_halo_cats.py 30
srun --time=1 python predict_save_halo_cats.py 31
srun --time=1 python predict_save_halo_cats.py 32
srun --time=1 python predict_save_halo_cats.py 33
srun --time=1 python predict_save_halo_cats.py 34
srun --time=1 python predict_save_halo_cats.py 35
srun --time=1 python predict_save_halo_cats.py 36
srun --time=1 python predict_save_halo_cats.py 37
srun --time=1 python predict_save_halo_cats.py 38
srun --time=1 python predict_save_halo_cats.py 39
srun --time=1 python predict_save_halo_cats.py 40
srun --time=1 python predict_save_halo_cats.py 41
srun --time=1 python predict_save_halo_cats.py 42
srun --time=1 python predict_save_halo_cats.py 43
srun --time=1 python predict_save_halo_cats.py 44
srun --time=1 python predict_save_halo_cats.py 45
srun --time=1 python predict_save_halo_cats.py 46
srun --time=1 python predict_save_halo_cats.py 47
srun --time=1 python predict_save_halo_cats.py 48
srun --time=1 python predict_save_halo_cats.py 49
srun --time=1 python predict_save_halo_cats.py 50
srun --time=1 python predict_save_halo_cats.py 51
srun --time=1 python predict_save_halo_cats.py 52
srun --time=1 python predict_save_halo_cats.py 53
srun --time=1 python predict_save_halo_cats.py 54
srun --time=1 python predict_save_halo_cats.py 55
srun --time=1 python predict_save_halo_cats.py 56
srun --time=1 python predict_save_halo_cats.py 57
srun --time=1 python predict_save_halo_cats.py 58
srun --time=1 python predict_save_halo_cats.py 59
srun --time=1 python predict_save_halo_cats.py 60
srun --time=1 python predict_save_halo_cats.py 61
srun --time=1 python predict_save_halo_cats.py 62
srun --time=1 python predict_save_halo_cats.py 63
srun --time=1 python predict_save_halo_cats.py 64
srun --time=1 python predict_save_halo_cats.py 65
srun --time=1 python predict_save_halo_cats.py 66
srun --time=1 python predict_save_halo_cats.py 67
srun --time=1 python predict_save_halo_cats.py 68
srun --time=1 python predict_save_halo_cats.py 69
srun --time=1 python predict_save_halo_cats.py 70
srun --time=1 python predict_save_halo_cats.py 71
srun --time=1 python predict_save_halo_cats.py 72
srun --time=1 python predict_save_halo_cats.py 73
srun --time=1 python predict_save_halo_cats.py 74
srun --time=1 python predict_save_halo_cats.py 75
srun --time=1 python predict_save_halo_cats.py 76
srun --time=1 python predict_save_halo_cats.py 77
srun --time=1 python predict_save_halo_cats.py 78
srun --time=1 python predict_save_halo_cats.py 79
srun --time=1 python predict_save_halo_cats.py 80
srun --time=1 python predict_save_halo_cats.py 81
srun --time=1 python predict_save_halo_cats.py 82
srun --time=1 python predict_save_halo_cats.py 83
srun --time=1 python predict_save_halo_cats.py 84
srun --time=1 python predict_save_halo_cats.py 85
srun --time=1 python predict_save_halo_cats.py 86
srun --time=1 python predict_save_halo_cats.py 87
srun --time=1 python predict_save_halo_cats.py 88
srun --time=1 python predict_save_halo_cats.py 89
srun --time=1 python predict_save_halo_cats.py 90
srun --time=1 python predict_save_halo_cats.py 91
srun --time=1 python predict_save_halo_cats.py 92
srun --time=1 python predict_save_halo_cats.py 93
srun --time=1 python predict_save_halo_cats.py 94
srun --time=1 python predict_save_halo_cats.py 95
srun --time=1 python predict_save_halo_cats.py 96
srun --time=1 python predict_save_halo_cats.py 97
srun --time=1 python predict_save_halo_cats.py 98
srun --time=1 python predict_save_halo_cats.py 99
srun --time=1 python predict_save_halo_cats.py 100
srun --time=1 python predict_save_halo_cats.py 101
srun --time=1 python predict_save_halo_cats.py 102
srun --time=1 python predict_save_halo_cats.py 103
srun --time=1 python predict_save_halo_cats.py 104
srun --time=1 python predict_save_halo_cats.py 105
srun --time=1 python predict_save_halo_cats.py 106
srun --time=1 python predict_save_halo_cats.py 107
srun --time=1 python predict_save_halo_cats.py 108
srun --time=1 python predict_save_halo_cats.py 109
srun --time=1 python predict_save_halo_cats.py 110
srun --time=1 python predict_save_halo_cats.py 111
srun --time=1 python predict_save_halo_cats.py 112
srun --time=1 python predict_save_halo_cats.py 113
srun --time=1 python predict_save_halo_cats.py 114
srun --time=1 python predict_save_halo_cats.py 115
srun --time=1 python predict_save_halo_cats.py 116
srun --time=1 python predict_save_halo_cats.py 117
srun --time=1 python predict_save_halo_cats.py 118
srun --time=1 python predict_save_halo_cats.py 119
srun --time=1 python predict_save_halo_cats.py 120
srun --time=1 python predict_save_halo_cats.py 121
srun --time=1 python predict_save_halo_cats.py 122
srun --time=1 python predict_save_halo_cats.py 123
srun --time=1 python predict_save_halo_cats.py 124
srun --time=1 python predict_save_halo_cats.py 125
srun --time=1 python predict_save_halo_cats.py 126
srun --time=1 python predict_save_halo_cats.py 127
srun --time=1 python predict_save_halo_cats.py 128
srun --time=1 python predict_save_halo_cats.py 129
srun --time=1 python predict_save_halo_cats.py 130
srun --time=1 python predict_save_halo_cats.py 131
srun --time=1 python predict_save_halo_cats.py 132
srun --time=1 python predict_save_halo_cats.py 133
srun --time=1 python predict_save_halo_cats.py 134
srun --time=1 python predict_save_halo_cats.py 135
srun --time=1 python predict_save_halo_cats.py 136
srun --time=1 python predict_save_halo_cats.py 137
srun --time=1 python predict_save_halo_cats.py 138
srun --time=1 python predict_save_halo_cats.py 139
srun --time=1 python predict_save_halo_cats.py 140
srun --time=1 python predict_save_halo_cats.py 141
srun --time=1 python predict_save_halo_cats.py 142
srun --time=1 python predict_save_halo_cats.py 143
srun --time=1 python predict_save_halo_cats.py 144
srun --time=1 python predict_save_halo_cats.py 145
srun --time=1 python predict_save_halo_cats.py 146
srun --time=1 python predict_save_halo_cats.py 147
srun --time=1 python predict_save_halo_cats.py 148
srun --time=1 python predict_save_halo_cats.py 149
srun --time=1 python predict_save_halo_cats.py 150
srun --time=1 python predict_save_halo_cats.py 151
srun --time=1 python predict_save_halo_cats.py 152
srun --time=1 python predict_save_halo_cats.py 153
srun --time=1 python predict_save_halo_cats.py 154
srun --time=1 python predict_save_halo_cats.py 155
srun --time=1 python predict_save_halo_cats.py 156
srun --time=1 python predict_save_halo_cats.py 157
srun --time=1 python predict_save_halo_cats.py 158
srun --time=1 python predict_save_halo_cats.py 159
srun --time=1 python predict_save_halo_cats.py 160
srun --time=1 python predict_save_halo_cats.py 161
srun --time=1 python predict_save_halo_cats.py 162
srun --time=1 python predict_save_halo_cats.py 163
srun --time=1 python predict_save_halo_cats.py 164
srun --time=1 python predict_save_halo_cats.py 165
srun --time=1 python predict_save_halo_cats.py 166
srun --time=1 python predict_save_halo_cats.py 167
srun --time=1 python predict_save_halo_cats.py 168
srun --time=1 python predict_save_halo_cats.py 169
srun --time=1 python predict_save_halo_cats.py 170
srun --time=1 python predict_save_halo_cats.py 171
srun --time=1 python predict_save_halo_cats.py 172
srun --time=1 python predict_save_halo_cats.py 173
srun --time=1 python predict_save_halo_cats.py 174
srun --time=1 python predict_save_halo_cats.py 175
srun --time=1 python predict_save_halo_cats.py 176
srun --time=1 python predict_save_halo_cats.py 177
srun --time=1 python predict_save_halo_cats.py 178
srun --time=1 python predict_save_halo_cats.py 179
srun --time=1 python predict_save_halo_cats.py 180
srun --time=1 python predict_save_halo_cats.py 181
srun --time=1 python predict_save_halo_cats.py 182
srun --time=1 python predict_save_halo_cats.py 183
srun --time=1 python predict_save_halo_cats.py 184
srun --time=1 python predict_save_halo_cats.py 185
srun --time=1 python predict_save_halo_cats.py 186
srun --time=1 python predict_save_halo_cats.py 187
srun --time=1 python predict_save_halo_cats.py 188
srun --time=1 python predict_save_halo_cats.py 189
srun --time=1 python predict_save_halo_cats.py 190
srun --time=1 python predict_save_halo_cats.py 191
srun --time=1 python predict_save_halo_cats.py 192
srun --time=1 python predict_save_halo_cats.py 193
srun --time=1 python predict_save_halo_cats.py 194
srun --time=1 python predict_save_halo_cats.py 195
srun --time=1 python predict_save_halo_cats.py 196
srun --time=1 python predict_save_halo_cats.py 197
srun --time=1 python predict_save_halo_cats.py 198
srun --time=1 python predict_save_halo_cats.py 199


echo "All done!"
