#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-gpu=12
#SBATCH --time=8:00:00
#SBATCH --job-name=save_cats
#SBATCH -p gpu
#SBATCH --mem=256G
#SBATCH --gpus-per-node=1
#SBATCH --output=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.out
#SBATCH --error=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.err

module purge
module load python
module load cuda
module load cudnn
module load nccl
source ~/miniconda3/bin/activate ili-sbi

cd /mnt/home/spandey/ceph/CHARM/charm/


srun --time=1 python predict_save_halo_cats.py 1600
srun --time=1 python predict_save_halo_cats.py 1601
srun --time=1 python predict_save_halo_cats.py 1602
srun --time=1 python predict_save_halo_cats.py 1603
srun --time=1 python predict_save_halo_cats.py 1604
srun --time=1 python predict_save_halo_cats.py 1605
srun --time=1 python predict_save_halo_cats.py 1606
srun --time=1 python predict_save_halo_cats.py 1607
srun --time=1 python predict_save_halo_cats.py 1608
srun --time=1 python predict_save_halo_cats.py 1609
srun --time=1 python predict_save_halo_cats.py 1610
srun --time=1 python predict_save_halo_cats.py 1611
srun --time=1 python predict_save_halo_cats.py 1612
srun --time=1 python predict_save_halo_cats.py 1613
srun --time=1 python predict_save_halo_cats.py 1614
srun --time=1 python predict_save_halo_cats.py 1615
srun --time=1 python predict_save_halo_cats.py 1616
srun --time=1 python predict_save_halo_cats.py 1617
srun --time=1 python predict_save_halo_cats.py 1618
srun --time=1 python predict_save_halo_cats.py 1619
srun --time=1 python predict_save_halo_cats.py 1620
srun --time=1 python predict_save_halo_cats.py 1621
srun --time=1 python predict_save_halo_cats.py 1622
srun --time=1 python predict_save_halo_cats.py 1623
srun --time=1 python predict_save_halo_cats.py 1624
srun --time=1 python predict_save_halo_cats.py 1625
srun --time=1 python predict_save_halo_cats.py 1626
srun --time=1 python predict_save_halo_cats.py 1627
srun --time=1 python predict_save_halo_cats.py 1628
srun --time=1 python predict_save_halo_cats.py 1629
srun --time=1 python predict_save_halo_cats.py 1630
srun --time=1 python predict_save_halo_cats.py 1631
srun --time=1 python predict_save_halo_cats.py 1632
srun --time=1 python predict_save_halo_cats.py 1633
srun --time=1 python predict_save_halo_cats.py 1634
srun --time=1 python predict_save_halo_cats.py 1635
srun --time=1 python predict_save_halo_cats.py 1636
srun --time=1 python predict_save_halo_cats.py 1637
srun --time=1 python predict_save_halo_cats.py 1638
srun --time=1 python predict_save_halo_cats.py 1639
srun --time=1 python predict_save_halo_cats.py 1640
srun --time=1 python predict_save_halo_cats.py 1641
srun --time=1 python predict_save_halo_cats.py 1642
srun --time=1 python predict_save_halo_cats.py 1643
srun --time=1 python predict_save_halo_cats.py 1644
srun --time=1 python predict_save_halo_cats.py 1645
srun --time=1 python predict_save_halo_cats.py 1646
srun --time=1 python predict_save_halo_cats.py 1647
srun --time=1 python predict_save_halo_cats.py 1648
srun --time=1 python predict_save_halo_cats.py 1649
srun --time=1 python predict_save_halo_cats.py 1650
srun --time=1 python predict_save_halo_cats.py 1651
srun --time=1 python predict_save_halo_cats.py 1652
srun --time=1 python predict_save_halo_cats.py 1653
srun --time=1 python predict_save_halo_cats.py 1654
srun --time=1 python predict_save_halo_cats.py 1655
srun --time=1 python predict_save_halo_cats.py 1656
srun --time=1 python predict_save_halo_cats.py 1657
srun --time=1 python predict_save_halo_cats.py 1658
srun --time=1 python predict_save_halo_cats.py 1659
srun --time=1 python predict_save_halo_cats.py 1660
srun --time=1 python predict_save_halo_cats.py 1661
srun --time=1 python predict_save_halo_cats.py 1662
srun --time=1 python predict_save_halo_cats.py 1663
srun --time=1 python predict_save_halo_cats.py 1664
srun --time=1 python predict_save_halo_cats.py 1665
srun --time=1 python predict_save_halo_cats.py 1666
srun --time=1 python predict_save_halo_cats.py 1667
srun --time=1 python predict_save_halo_cats.py 1668
srun --time=1 python predict_save_halo_cats.py 1669
srun --time=1 python predict_save_halo_cats.py 1670
srun --time=1 python predict_save_halo_cats.py 1671
srun --time=1 python predict_save_halo_cats.py 1672
srun --time=1 python predict_save_halo_cats.py 1673
srun --time=1 python predict_save_halo_cats.py 1674
srun --time=1 python predict_save_halo_cats.py 1675
srun --time=1 python predict_save_halo_cats.py 1676
srun --time=1 python predict_save_halo_cats.py 1677
srun --time=1 python predict_save_halo_cats.py 1678
srun --time=1 python predict_save_halo_cats.py 1679
srun --time=1 python predict_save_halo_cats.py 1680
srun --time=1 python predict_save_halo_cats.py 1681
srun --time=1 python predict_save_halo_cats.py 1682
srun --time=1 python predict_save_halo_cats.py 1683
srun --time=1 python predict_save_halo_cats.py 1684
srun --time=1 python predict_save_halo_cats.py 1685
srun --time=1 python predict_save_halo_cats.py 1686
srun --time=1 python predict_save_halo_cats.py 1687
srun --time=1 python predict_save_halo_cats.py 1688
srun --time=1 python predict_save_halo_cats.py 1689
srun --time=1 python predict_save_halo_cats.py 1690
srun --time=1 python predict_save_halo_cats.py 1691
srun --time=1 python predict_save_halo_cats.py 1692
srun --time=1 python predict_save_halo_cats.py 1693
srun --time=1 python predict_save_halo_cats.py 1694
srun --time=1 python predict_save_halo_cats.py 1695
srun --time=1 python predict_save_halo_cats.py 1696
srun --time=1 python predict_save_halo_cats.py 1697
srun --time=1 python predict_save_halo_cats.py 1698
srun --time=1 python predict_save_halo_cats.py 1699
srun --time=1 python predict_save_halo_cats.py 1700
srun --time=1 python predict_save_halo_cats.py 1701
srun --time=1 python predict_save_halo_cats.py 1702
srun --time=1 python predict_save_halo_cats.py 1703
srun --time=1 python predict_save_halo_cats.py 1704
srun --time=1 python predict_save_halo_cats.py 1705
srun --time=1 python predict_save_halo_cats.py 1706
srun --time=1 python predict_save_halo_cats.py 1707
srun --time=1 python predict_save_halo_cats.py 1708
srun --time=1 python predict_save_halo_cats.py 1709
srun --time=1 python predict_save_halo_cats.py 1710
srun --time=1 python predict_save_halo_cats.py 1711
srun --time=1 python predict_save_halo_cats.py 1712
srun --time=1 python predict_save_halo_cats.py 1713
srun --time=1 python predict_save_halo_cats.py 1714
srun --time=1 python predict_save_halo_cats.py 1715
srun --time=1 python predict_save_halo_cats.py 1716
srun --time=1 python predict_save_halo_cats.py 1717
srun --time=1 python predict_save_halo_cats.py 1718
srun --time=1 python predict_save_halo_cats.py 1719
srun --time=1 python predict_save_halo_cats.py 1720
srun --time=1 python predict_save_halo_cats.py 1721
srun --time=1 python predict_save_halo_cats.py 1722
srun --time=1 python predict_save_halo_cats.py 1723
srun --time=1 python predict_save_halo_cats.py 1724
srun --time=1 python predict_save_halo_cats.py 1725
srun --time=1 python predict_save_halo_cats.py 1726
srun --time=1 python predict_save_halo_cats.py 1727
srun --time=1 python predict_save_halo_cats.py 1728
srun --time=1 python predict_save_halo_cats.py 1729
srun --time=1 python predict_save_halo_cats.py 1730
srun --time=1 python predict_save_halo_cats.py 1731
srun --time=1 python predict_save_halo_cats.py 1732
srun --time=1 python predict_save_halo_cats.py 1733
srun --time=1 python predict_save_halo_cats.py 1734
srun --time=1 python predict_save_halo_cats.py 1735
srun --time=1 python predict_save_halo_cats.py 1736
srun --time=1 python predict_save_halo_cats.py 1737
srun --time=1 python predict_save_halo_cats.py 1738
srun --time=1 python predict_save_halo_cats.py 1739
srun --time=1 python predict_save_halo_cats.py 1740
srun --time=1 python predict_save_halo_cats.py 1741
srun --time=1 python predict_save_halo_cats.py 1742
srun --time=1 python predict_save_halo_cats.py 1743
srun --time=1 python predict_save_halo_cats.py 1744
srun --time=1 python predict_save_halo_cats.py 1745
srun --time=1 python predict_save_halo_cats.py 1746
srun --time=1 python predict_save_halo_cats.py 1747
srun --time=1 python predict_save_halo_cats.py 1748
srun --time=1 python predict_save_halo_cats.py 1749
srun --time=1 python predict_save_halo_cats.py 1750
srun --time=1 python predict_save_halo_cats.py 1751
srun --time=1 python predict_save_halo_cats.py 1752
srun --time=1 python predict_save_halo_cats.py 1753
srun --time=1 python predict_save_halo_cats.py 1754
srun --time=1 python predict_save_halo_cats.py 1755
srun --time=1 python predict_save_halo_cats.py 1756
srun --time=1 python predict_save_halo_cats.py 1757
srun --time=1 python predict_save_halo_cats.py 1758
srun --time=1 python predict_save_halo_cats.py 1759
srun --time=1 python predict_save_halo_cats.py 1760
srun --time=1 python predict_save_halo_cats.py 1761
srun --time=1 python predict_save_halo_cats.py 1762
srun --time=1 python predict_save_halo_cats.py 1763
srun --time=1 python predict_save_halo_cats.py 1764
srun --time=1 python predict_save_halo_cats.py 1765
srun --time=1 python predict_save_halo_cats.py 1766
srun --time=1 python predict_save_halo_cats.py 1767
srun --time=1 python predict_save_halo_cats.py 1768
srun --time=1 python predict_save_halo_cats.py 1769
srun --time=1 python predict_save_halo_cats.py 1770
srun --time=1 python predict_save_halo_cats.py 1771
srun --time=1 python predict_save_halo_cats.py 1772
srun --time=1 python predict_save_halo_cats.py 1773
srun --time=1 python predict_save_halo_cats.py 1774
srun --time=1 python predict_save_halo_cats.py 1775
srun --time=1 python predict_save_halo_cats.py 1776
srun --time=1 python predict_save_halo_cats.py 1777
srun --time=1 python predict_save_halo_cats.py 1778
srun --time=1 python predict_save_halo_cats.py 1779
srun --time=1 python predict_save_halo_cats.py 1780
srun --time=1 python predict_save_halo_cats.py 1781
srun --time=1 python predict_save_halo_cats.py 1782
srun --time=1 python predict_save_halo_cats.py 1783
srun --time=1 python predict_save_halo_cats.py 1784
srun --time=1 python predict_save_halo_cats.py 1785
srun --time=1 python predict_save_halo_cats.py 1786
srun --time=1 python predict_save_halo_cats.py 1787
srun --time=1 python predict_save_halo_cats.py 1788
srun --time=1 python predict_save_halo_cats.py 1789
srun --time=1 python predict_save_halo_cats.py 1790
srun --time=1 python predict_save_halo_cats.py 1791
srun --time=1 python predict_save_halo_cats.py 1792
srun --time=1 python predict_save_halo_cats.py 1793
srun --time=1 python predict_save_halo_cats.py 1794
srun --time=1 python predict_save_halo_cats.py 1795
srun --time=1 python predict_save_halo_cats.py 1796
srun --time=1 python predict_save_halo_cats.py 1797
srun --time=1 python predict_save_halo_cats.py 1798
srun --time=1 python predict_save_halo_cats.py 1799


echo "All done!"
