#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-gpu=12
#SBATCH --time=8:00:00
#SBATCH --job-name=save_cats
#SBATCH -p gpu
#SBATCH --mem=256G
#SBATCH --gpus-per-node=1
#SBATCH --output=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.out
#SBATCH --error=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.err

module purge
module load python
module load cuda
module load cudnn
module load nccl
source ~/miniconda3/bin/activate ili-sbi

cd /mnt/home/spandey/ceph/CHARM/charm/


srun --time=1 python predict_save_halo_cats.py 200
srun --time=1 python predict_save_halo_cats.py 201
srun --time=1 python predict_save_halo_cats.py 202
srun --time=1 python predict_save_halo_cats.py 203
srun --time=1 python predict_save_halo_cats.py 204
srun --time=1 python predict_save_halo_cats.py 205
srun --time=1 python predict_save_halo_cats.py 206
srun --time=1 python predict_save_halo_cats.py 207
srun --time=1 python predict_save_halo_cats.py 208
srun --time=1 python predict_save_halo_cats.py 209
srun --time=1 python predict_save_halo_cats.py 210
srun --time=1 python predict_save_halo_cats.py 211
srun --time=1 python predict_save_halo_cats.py 212
srun --time=1 python predict_save_halo_cats.py 213
srun --time=1 python predict_save_halo_cats.py 214
srun --time=1 python predict_save_halo_cats.py 215
srun --time=1 python predict_save_halo_cats.py 216
srun --time=1 python predict_save_halo_cats.py 217
srun --time=1 python predict_save_halo_cats.py 218
srun --time=1 python predict_save_halo_cats.py 219
srun --time=1 python predict_save_halo_cats.py 220
srun --time=1 python predict_save_halo_cats.py 221
srun --time=1 python predict_save_halo_cats.py 222
srun --time=1 python predict_save_halo_cats.py 223
srun --time=1 python predict_save_halo_cats.py 224
srun --time=1 python predict_save_halo_cats.py 225
srun --time=1 python predict_save_halo_cats.py 226
srun --time=1 python predict_save_halo_cats.py 227
srun --time=1 python predict_save_halo_cats.py 228
srun --time=1 python predict_save_halo_cats.py 229
srun --time=1 python predict_save_halo_cats.py 230
srun --time=1 python predict_save_halo_cats.py 231
srun --time=1 python predict_save_halo_cats.py 232
srun --time=1 python predict_save_halo_cats.py 233
srun --time=1 python predict_save_halo_cats.py 234
srun --time=1 python predict_save_halo_cats.py 235
srun --time=1 python predict_save_halo_cats.py 236
srun --time=1 python predict_save_halo_cats.py 237
srun --time=1 python predict_save_halo_cats.py 238
srun --time=1 python predict_save_halo_cats.py 239
srun --time=1 python predict_save_halo_cats.py 240
srun --time=1 python predict_save_halo_cats.py 241
srun --time=1 python predict_save_halo_cats.py 242
srun --time=1 python predict_save_halo_cats.py 243
srun --time=1 python predict_save_halo_cats.py 244
srun --time=1 python predict_save_halo_cats.py 245
srun --time=1 python predict_save_halo_cats.py 246
srun --time=1 python predict_save_halo_cats.py 247
srun --time=1 python predict_save_halo_cats.py 248
srun --time=1 python predict_save_halo_cats.py 249
srun --time=1 python predict_save_halo_cats.py 250
srun --time=1 python predict_save_halo_cats.py 251
srun --time=1 python predict_save_halo_cats.py 252
srun --time=1 python predict_save_halo_cats.py 253
srun --time=1 python predict_save_halo_cats.py 254
srun --time=1 python predict_save_halo_cats.py 255
srun --time=1 python predict_save_halo_cats.py 256
srun --time=1 python predict_save_halo_cats.py 257
srun --time=1 python predict_save_halo_cats.py 258
srun --time=1 python predict_save_halo_cats.py 259
srun --time=1 python predict_save_halo_cats.py 260
srun --time=1 python predict_save_halo_cats.py 261
srun --time=1 python predict_save_halo_cats.py 262
srun --time=1 python predict_save_halo_cats.py 263
srun --time=1 python predict_save_halo_cats.py 264
srun --time=1 python predict_save_halo_cats.py 265
srun --time=1 python predict_save_halo_cats.py 266
srun --time=1 python predict_save_halo_cats.py 267
srun --time=1 python predict_save_halo_cats.py 268
srun --time=1 python predict_save_halo_cats.py 269
srun --time=1 python predict_save_halo_cats.py 270
srun --time=1 python predict_save_halo_cats.py 271
srun --time=1 python predict_save_halo_cats.py 272
srun --time=1 python predict_save_halo_cats.py 273
srun --time=1 python predict_save_halo_cats.py 274
srun --time=1 python predict_save_halo_cats.py 275
srun --time=1 python predict_save_halo_cats.py 276
srun --time=1 python predict_save_halo_cats.py 277
srun --time=1 python predict_save_halo_cats.py 278
srun --time=1 python predict_save_halo_cats.py 279
srun --time=1 python predict_save_halo_cats.py 280
srun --time=1 python predict_save_halo_cats.py 281
srun --time=1 python predict_save_halo_cats.py 282
srun --time=1 python predict_save_halo_cats.py 283
srun --time=1 python predict_save_halo_cats.py 284
srun --time=1 python predict_save_halo_cats.py 285
srun --time=1 python predict_save_halo_cats.py 286
srun --time=1 python predict_save_halo_cats.py 287
srun --time=1 python predict_save_halo_cats.py 288
srun --time=1 python predict_save_halo_cats.py 289
srun --time=1 python predict_save_halo_cats.py 290
srun --time=1 python predict_save_halo_cats.py 291
srun --time=1 python predict_save_halo_cats.py 292
srun --time=1 python predict_save_halo_cats.py 293
srun --time=1 python predict_save_halo_cats.py 294
srun --time=1 python predict_save_halo_cats.py 295
srun --time=1 python predict_save_halo_cats.py 296
srun --time=1 python predict_save_halo_cats.py 297
srun --time=1 python predict_save_halo_cats.py 298
srun --time=1 python predict_save_halo_cats.py 299
srun --time=1 python predict_save_halo_cats.py 300
srun --time=1 python predict_save_halo_cats.py 301
srun --time=1 python predict_save_halo_cats.py 302
srun --time=1 python predict_save_halo_cats.py 303
srun --time=1 python predict_save_halo_cats.py 304
srun --time=1 python predict_save_halo_cats.py 305
srun --time=1 python predict_save_halo_cats.py 306
srun --time=1 python predict_save_halo_cats.py 307
srun --time=1 python predict_save_halo_cats.py 308
srun --time=1 python predict_save_halo_cats.py 309
srun --time=1 python predict_save_halo_cats.py 310
srun --time=1 python predict_save_halo_cats.py 311
srun --time=1 python predict_save_halo_cats.py 312
srun --time=1 python predict_save_halo_cats.py 313
srun --time=1 python predict_save_halo_cats.py 314
srun --time=1 python predict_save_halo_cats.py 315
srun --time=1 python predict_save_halo_cats.py 316
srun --time=1 python predict_save_halo_cats.py 317
srun --time=1 python predict_save_halo_cats.py 318
srun --time=1 python predict_save_halo_cats.py 319
srun --time=1 python predict_save_halo_cats.py 320
srun --time=1 python predict_save_halo_cats.py 321
srun --time=1 python predict_save_halo_cats.py 322
srun --time=1 python predict_save_halo_cats.py 323
srun --time=1 python predict_save_halo_cats.py 324
srun --time=1 python predict_save_halo_cats.py 325
srun --time=1 python predict_save_halo_cats.py 326
srun --time=1 python predict_save_halo_cats.py 327
srun --time=1 python predict_save_halo_cats.py 328
srun --time=1 python predict_save_halo_cats.py 329
srun --time=1 python predict_save_halo_cats.py 330
srun --time=1 python predict_save_halo_cats.py 331
srun --time=1 python predict_save_halo_cats.py 332
srun --time=1 python predict_save_halo_cats.py 333
srun --time=1 python predict_save_halo_cats.py 334
srun --time=1 python predict_save_halo_cats.py 335
srun --time=1 python predict_save_halo_cats.py 336
srun --time=1 python predict_save_halo_cats.py 337
srun --time=1 python predict_save_halo_cats.py 338
srun --time=1 python predict_save_halo_cats.py 339
srun --time=1 python predict_save_halo_cats.py 340
srun --time=1 python predict_save_halo_cats.py 341
srun --time=1 python predict_save_halo_cats.py 342
srun --time=1 python predict_save_halo_cats.py 343
srun --time=1 python predict_save_halo_cats.py 344
srun --time=1 python predict_save_halo_cats.py 345
srun --time=1 python predict_save_halo_cats.py 346
srun --time=1 python predict_save_halo_cats.py 347
srun --time=1 python predict_save_halo_cats.py 348
srun --time=1 python predict_save_halo_cats.py 349
srun --time=1 python predict_save_halo_cats.py 350
srun --time=1 python predict_save_halo_cats.py 351
srun --time=1 python predict_save_halo_cats.py 352
srun --time=1 python predict_save_halo_cats.py 353
srun --time=1 python predict_save_halo_cats.py 354
srun --time=1 python predict_save_halo_cats.py 355
srun --time=1 python predict_save_halo_cats.py 356
srun --time=1 python predict_save_halo_cats.py 357
srun --time=1 python predict_save_halo_cats.py 358
srun --time=1 python predict_save_halo_cats.py 359
srun --time=1 python predict_save_halo_cats.py 360
srun --time=1 python predict_save_halo_cats.py 361
srun --time=1 python predict_save_halo_cats.py 362
srun --time=1 python predict_save_halo_cats.py 363
srun --time=1 python predict_save_halo_cats.py 364
srun --time=1 python predict_save_halo_cats.py 365
srun --time=1 python predict_save_halo_cats.py 366
srun --time=1 python predict_save_halo_cats.py 367
srun --time=1 python predict_save_halo_cats.py 368
srun --time=1 python predict_save_halo_cats.py 369
srun --time=1 python predict_save_halo_cats.py 370
srun --time=1 python predict_save_halo_cats.py 371
srun --time=1 python predict_save_halo_cats.py 372
srun --time=1 python predict_save_halo_cats.py 373
srun --time=1 python predict_save_halo_cats.py 374
srun --time=1 python predict_save_halo_cats.py 375
srun --time=1 python predict_save_halo_cats.py 376
srun --time=1 python predict_save_halo_cats.py 377
srun --time=1 python predict_save_halo_cats.py 378
srun --time=1 python predict_save_halo_cats.py 379
srun --time=1 python predict_save_halo_cats.py 380
srun --time=1 python predict_save_halo_cats.py 381
srun --time=1 python predict_save_halo_cats.py 382
srun --time=1 python predict_save_halo_cats.py 383
srun --time=1 python predict_save_halo_cats.py 384
srun --time=1 python predict_save_halo_cats.py 385
srun --time=1 python predict_save_halo_cats.py 386
srun --time=1 python predict_save_halo_cats.py 387
srun --time=1 python predict_save_halo_cats.py 388
srun --time=1 python predict_save_halo_cats.py 389
srun --time=1 python predict_save_halo_cats.py 390
srun --time=1 python predict_save_halo_cats.py 391
srun --time=1 python predict_save_halo_cats.py 392
srun --time=1 python predict_save_halo_cats.py 393
srun --time=1 python predict_save_halo_cats.py 394
srun --time=1 python predict_save_halo_cats.py 395
srun --time=1 python predict_save_halo_cats.py 396
srun --time=1 python predict_save_halo_cats.py 397
srun --time=1 python predict_save_halo_cats.py 398
srun --time=1 python predict_save_halo_cats.py 399


echo "All done!"
