#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-gpu=12
#SBATCH --time=8:00:00
#SBATCH --job-name=save_cats
#SBATCH -p gpu
#SBATCH --mem=256G
#SBATCH --gpus-per-node=1
#SBATCH --output=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.out
#SBATCH --error=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.err

module purge
module load python
module load cuda
module load cudnn
module load nccl
source ~/miniconda3/bin/activate ili-sbi

cd /mnt/home/spandey/ceph/CHARM/charm/


srun --time=1 python predict_save_halo_cats.py 1000
srun --time=1 python predict_save_halo_cats.py 1001
srun --time=1 python predict_save_halo_cats.py 1002
srun --time=1 python predict_save_halo_cats.py 1003
srun --time=1 python predict_save_halo_cats.py 1004
srun --time=1 python predict_save_halo_cats.py 1005
srun --time=1 python predict_save_halo_cats.py 1006
srun --time=1 python predict_save_halo_cats.py 1007
srun --time=1 python predict_save_halo_cats.py 1008
srun --time=1 python predict_save_halo_cats.py 1009
srun --time=1 python predict_save_halo_cats.py 1010
srun --time=1 python predict_save_halo_cats.py 1011
srun --time=1 python predict_save_halo_cats.py 1012
srun --time=1 python predict_save_halo_cats.py 1013
srun --time=1 python predict_save_halo_cats.py 1014
srun --time=1 python predict_save_halo_cats.py 1015
srun --time=1 python predict_save_halo_cats.py 1016
srun --time=1 python predict_save_halo_cats.py 1017
srun --time=1 python predict_save_halo_cats.py 1018
srun --time=1 python predict_save_halo_cats.py 1019
srun --time=1 python predict_save_halo_cats.py 1020
srun --time=1 python predict_save_halo_cats.py 1021
srun --time=1 python predict_save_halo_cats.py 1022
srun --time=1 python predict_save_halo_cats.py 1023
srun --time=1 python predict_save_halo_cats.py 1024
srun --time=1 python predict_save_halo_cats.py 1025
srun --time=1 python predict_save_halo_cats.py 1026
srun --time=1 python predict_save_halo_cats.py 1027
srun --time=1 python predict_save_halo_cats.py 1028
srun --time=1 python predict_save_halo_cats.py 1029
srun --time=1 python predict_save_halo_cats.py 1030
srun --time=1 python predict_save_halo_cats.py 1031
srun --time=1 python predict_save_halo_cats.py 1032
srun --time=1 python predict_save_halo_cats.py 1033
srun --time=1 python predict_save_halo_cats.py 1034
srun --time=1 python predict_save_halo_cats.py 1035
srun --time=1 python predict_save_halo_cats.py 1036
srun --time=1 python predict_save_halo_cats.py 1037
srun --time=1 python predict_save_halo_cats.py 1038
srun --time=1 python predict_save_halo_cats.py 1039
srun --time=1 python predict_save_halo_cats.py 1040
srun --time=1 python predict_save_halo_cats.py 1041
srun --time=1 python predict_save_halo_cats.py 1042
srun --time=1 python predict_save_halo_cats.py 1043
srun --time=1 python predict_save_halo_cats.py 1044
srun --time=1 python predict_save_halo_cats.py 1045
srun --time=1 python predict_save_halo_cats.py 1046
srun --time=1 python predict_save_halo_cats.py 1047
srun --time=1 python predict_save_halo_cats.py 1048
srun --time=1 python predict_save_halo_cats.py 1049
srun --time=1 python predict_save_halo_cats.py 1050
srun --time=1 python predict_save_halo_cats.py 1051
srun --time=1 python predict_save_halo_cats.py 1052
srun --time=1 python predict_save_halo_cats.py 1053
srun --time=1 python predict_save_halo_cats.py 1054
srun --time=1 python predict_save_halo_cats.py 1055
srun --time=1 python predict_save_halo_cats.py 1056
srun --time=1 python predict_save_halo_cats.py 1057
srun --time=1 python predict_save_halo_cats.py 1058
srun --time=1 python predict_save_halo_cats.py 1059
srun --time=1 python predict_save_halo_cats.py 1060
srun --time=1 python predict_save_halo_cats.py 1061
srun --time=1 python predict_save_halo_cats.py 1062
srun --time=1 python predict_save_halo_cats.py 1063
srun --time=1 python predict_save_halo_cats.py 1064
srun --time=1 python predict_save_halo_cats.py 1065
srun --time=1 python predict_save_halo_cats.py 1066
srun --time=1 python predict_save_halo_cats.py 1067
srun --time=1 python predict_save_halo_cats.py 1068
srun --time=1 python predict_save_halo_cats.py 1069
srun --time=1 python predict_save_halo_cats.py 1070
srun --time=1 python predict_save_halo_cats.py 1071
srun --time=1 python predict_save_halo_cats.py 1072
srun --time=1 python predict_save_halo_cats.py 1073
srun --time=1 python predict_save_halo_cats.py 1074
srun --time=1 python predict_save_halo_cats.py 1075
srun --time=1 python predict_save_halo_cats.py 1076
srun --time=1 python predict_save_halo_cats.py 1077
srun --time=1 python predict_save_halo_cats.py 1078
srun --time=1 python predict_save_halo_cats.py 1079
srun --time=1 python predict_save_halo_cats.py 1080
srun --time=1 python predict_save_halo_cats.py 1081
srun --time=1 python predict_save_halo_cats.py 1082
srun --time=1 python predict_save_halo_cats.py 1083
srun --time=1 python predict_save_halo_cats.py 1084
srun --time=1 python predict_save_halo_cats.py 1085
srun --time=1 python predict_save_halo_cats.py 1086
srun --time=1 python predict_save_halo_cats.py 1087
srun --time=1 python predict_save_halo_cats.py 1088
srun --time=1 python predict_save_halo_cats.py 1089
srun --time=1 python predict_save_halo_cats.py 1090
srun --time=1 python predict_save_halo_cats.py 1091
srun --time=1 python predict_save_halo_cats.py 1092
srun --time=1 python predict_save_halo_cats.py 1093
srun --time=1 python predict_save_halo_cats.py 1094
srun --time=1 python predict_save_halo_cats.py 1095
srun --time=1 python predict_save_halo_cats.py 1096
srun --time=1 python predict_save_halo_cats.py 1097
srun --time=1 python predict_save_halo_cats.py 1098
srun --time=1 python predict_save_halo_cats.py 1099
srun --time=1 python predict_save_halo_cats.py 1100
srun --time=1 python predict_save_halo_cats.py 1101
srun --time=1 python predict_save_halo_cats.py 1102
srun --time=1 python predict_save_halo_cats.py 1103
srun --time=1 python predict_save_halo_cats.py 1104
srun --time=1 python predict_save_halo_cats.py 1105
srun --time=1 python predict_save_halo_cats.py 1106
srun --time=1 python predict_save_halo_cats.py 1107
srun --time=1 python predict_save_halo_cats.py 1108
srun --time=1 python predict_save_halo_cats.py 1109
srun --time=1 python predict_save_halo_cats.py 1110
srun --time=1 python predict_save_halo_cats.py 1111
srun --time=1 python predict_save_halo_cats.py 1112
srun --time=1 python predict_save_halo_cats.py 1113
srun --time=1 python predict_save_halo_cats.py 1114
srun --time=1 python predict_save_halo_cats.py 1115
srun --time=1 python predict_save_halo_cats.py 1116
srun --time=1 python predict_save_halo_cats.py 1117
srun --time=1 python predict_save_halo_cats.py 1118
srun --time=1 python predict_save_halo_cats.py 1119
srun --time=1 python predict_save_halo_cats.py 1120
srun --time=1 python predict_save_halo_cats.py 1121
srun --time=1 python predict_save_halo_cats.py 1122
srun --time=1 python predict_save_halo_cats.py 1123
srun --time=1 python predict_save_halo_cats.py 1124
srun --time=1 python predict_save_halo_cats.py 1125
srun --time=1 python predict_save_halo_cats.py 1126
srun --time=1 python predict_save_halo_cats.py 1127
srun --time=1 python predict_save_halo_cats.py 1128
srun --time=1 python predict_save_halo_cats.py 1129
srun --time=1 python predict_save_halo_cats.py 1130
srun --time=1 python predict_save_halo_cats.py 1131
srun --time=1 python predict_save_halo_cats.py 1132
srun --time=1 python predict_save_halo_cats.py 1133
srun --time=1 python predict_save_halo_cats.py 1134
srun --time=1 python predict_save_halo_cats.py 1135
srun --time=1 python predict_save_halo_cats.py 1136
srun --time=1 python predict_save_halo_cats.py 1137
srun --time=1 python predict_save_halo_cats.py 1138
srun --time=1 python predict_save_halo_cats.py 1139
srun --time=1 python predict_save_halo_cats.py 1140
srun --time=1 python predict_save_halo_cats.py 1141
srun --time=1 python predict_save_halo_cats.py 1142
srun --time=1 python predict_save_halo_cats.py 1143
srun --time=1 python predict_save_halo_cats.py 1144
srun --time=1 python predict_save_halo_cats.py 1145
srun --time=1 python predict_save_halo_cats.py 1146
srun --time=1 python predict_save_halo_cats.py 1147
srun --time=1 python predict_save_halo_cats.py 1148
srun --time=1 python predict_save_halo_cats.py 1149
srun --time=1 python predict_save_halo_cats.py 1150
srun --time=1 python predict_save_halo_cats.py 1151
srun --time=1 python predict_save_halo_cats.py 1152
srun --time=1 python predict_save_halo_cats.py 1153
srun --time=1 python predict_save_halo_cats.py 1154
srun --time=1 python predict_save_halo_cats.py 1155
srun --time=1 python predict_save_halo_cats.py 1156
srun --time=1 python predict_save_halo_cats.py 1157
srun --time=1 python predict_save_halo_cats.py 1158
srun --time=1 python predict_save_halo_cats.py 1159
srun --time=1 python predict_save_halo_cats.py 1160
srun --time=1 python predict_save_halo_cats.py 1161
srun --time=1 python predict_save_halo_cats.py 1162
srun --time=1 python predict_save_halo_cats.py 1163
srun --time=1 python predict_save_halo_cats.py 1164
srun --time=1 python predict_save_halo_cats.py 1165
srun --time=1 python predict_save_halo_cats.py 1166
srun --time=1 python predict_save_halo_cats.py 1167
srun --time=1 python predict_save_halo_cats.py 1168
srun --time=1 python predict_save_halo_cats.py 1169
srun --time=1 python predict_save_halo_cats.py 1170
srun --time=1 python predict_save_halo_cats.py 1171
srun --time=1 python predict_save_halo_cats.py 1172
srun --time=1 python predict_save_halo_cats.py 1173
srun --time=1 python predict_save_halo_cats.py 1174
srun --time=1 python predict_save_halo_cats.py 1175
srun --time=1 python predict_save_halo_cats.py 1176
srun --time=1 python predict_save_halo_cats.py 1177
srun --time=1 python predict_save_halo_cats.py 1178
srun --time=1 python predict_save_halo_cats.py 1179
srun --time=1 python predict_save_halo_cats.py 1180
srun --time=1 python predict_save_halo_cats.py 1181
srun --time=1 python predict_save_halo_cats.py 1182
srun --time=1 python predict_save_halo_cats.py 1183
srun --time=1 python predict_save_halo_cats.py 1184
srun --time=1 python predict_save_halo_cats.py 1185
srun --time=1 python predict_save_halo_cats.py 1186
srun --time=1 python predict_save_halo_cats.py 1187
srun --time=1 python predict_save_halo_cats.py 1188
srun --time=1 python predict_save_halo_cats.py 1189
srun --time=1 python predict_save_halo_cats.py 1190
srun --time=1 python predict_save_halo_cats.py 1191
srun --time=1 python predict_save_halo_cats.py 1192
srun --time=1 python predict_save_halo_cats.py 1193
srun --time=1 python predict_save_halo_cats.py 1194
srun --time=1 python predict_save_halo_cats.py 1195
srun --time=1 python predict_save_halo_cats.py 1196
srun --time=1 python predict_save_halo_cats.py 1197
srun --time=1 python predict_save_halo_cats.py 1198
srun --time=1 python predict_save_halo_cats.py 1199


echo "All done!"
