#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-gpu=12
#SBATCH --time=8:00:00
#SBATCH --job-name=save_cats
#SBATCH -p gpu
#SBATCH --mem=256G
#SBATCH --gpus-per-node=1
#SBATCH --output=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.out
#SBATCH --error=/mnt/home/spandey/ceph/CHARM/run_scripts/slurm_logs/%x.%j.err

module purge
module load python
module load cuda
module load cudnn
module load nccl
source ~/miniconda3/bin/activate ili-sbi

cd /mnt/home/spandey/ceph/CHARM/charm/


srun --time=1 python predict_save_halo_cats.py 600
srun --time=1 python predict_save_halo_cats.py 601
srun --time=1 python predict_save_halo_cats.py 602
srun --time=1 python predict_save_halo_cats.py 603
srun --time=1 python predict_save_halo_cats.py 604
srun --time=1 python predict_save_halo_cats.py 605
srun --time=1 python predict_save_halo_cats.py 606
srun --time=1 python predict_save_halo_cats.py 607
srun --time=1 python predict_save_halo_cats.py 608
srun --time=1 python predict_save_halo_cats.py 609
srun --time=1 python predict_save_halo_cats.py 610
srun --time=1 python predict_save_halo_cats.py 611
srun --time=1 python predict_save_halo_cats.py 612
srun --time=1 python predict_save_halo_cats.py 613
srun --time=1 python predict_save_halo_cats.py 614
srun --time=1 python predict_save_halo_cats.py 615
srun --time=1 python predict_save_halo_cats.py 616
srun --time=1 python predict_save_halo_cats.py 617
srun --time=1 python predict_save_halo_cats.py 618
srun --time=1 python predict_save_halo_cats.py 619
srun --time=1 python predict_save_halo_cats.py 620
srun --time=1 python predict_save_halo_cats.py 621
srun --time=1 python predict_save_halo_cats.py 622
srun --time=1 python predict_save_halo_cats.py 623
srun --time=1 python predict_save_halo_cats.py 624
srun --time=1 python predict_save_halo_cats.py 625
srun --time=1 python predict_save_halo_cats.py 626
srun --time=1 python predict_save_halo_cats.py 627
srun --time=1 python predict_save_halo_cats.py 628
srun --time=1 python predict_save_halo_cats.py 629
srun --time=1 python predict_save_halo_cats.py 630
srun --time=1 python predict_save_halo_cats.py 631
srun --time=1 python predict_save_halo_cats.py 632
srun --time=1 python predict_save_halo_cats.py 633
srun --time=1 python predict_save_halo_cats.py 634
srun --time=1 python predict_save_halo_cats.py 635
srun --time=1 python predict_save_halo_cats.py 636
srun --time=1 python predict_save_halo_cats.py 637
srun --time=1 python predict_save_halo_cats.py 638
srun --time=1 python predict_save_halo_cats.py 639
srun --time=1 python predict_save_halo_cats.py 640
srun --time=1 python predict_save_halo_cats.py 641
srun --time=1 python predict_save_halo_cats.py 642
srun --time=1 python predict_save_halo_cats.py 643
srun --time=1 python predict_save_halo_cats.py 644
srun --time=1 python predict_save_halo_cats.py 645
srun --time=1 python predict_save_halo_cats.py 646
srun --time=1 python predict_save_halo_cats.py 647
srun --time=1 python predict_save_halo_cats.py 648
srun --time=1 python predict_save_halo_cats.py 649
srun --time=1 python predict_save_halo_cats.py 650
srun --time=1 python predict_save_halo_cats.py 651
srun --time=1 python predict_save_halo_cats.py 652
srun --time=1 python predict_save_halo_cats.py 653
srun --time=1 python predict_save_halo_cats.py 654
srun --time=1 python predict_save_halo_cats.py 655
srun --time=1 python predict_save_halo_cats.py 656
srun --time=1 python predict_save_halo_cats.py 657
srun --time=1 python predict_save_halo_cats.py 658
srun --time=1 python predict_save_halo_cats.py 659
srun --time=1 python predict_save_halo_cats.py 660
srun --time=1 python predict_save_halo_cats.py 661
srun --time=1 python predict_save_halo_cats.py 662
srun --time=1 python predict_save_halo_cats.py 663
srun --time=1 python predict_save_halo_cats.py 664
srun --time=1 python predict_save_halo_cats.py 665
srun --time=1 python predict_save_halo_cats.py 666
srun --time=1 python predict_save_halo_cats.py 667
srun --time=1 python predict_save_halo_cats.py 668
srun --time=1 python predict_save_halo_cats.py 669
srun --time=1 python predict_save_halo_cats.py 670
srun --time=1 python predict_save_halo_cats.py 671
srun --time=1 python predict_save_halo_cats.py 672
srun --time=1 python predict_save_halo_cats.py 673
srun --time=1 python predict_save_halo_cats.py 674
srun --time=1 python predict_save_halo_cats.py 675
srun --time=1 python predict_save_halo_cats.py 676
srun --time=1 python predict_save_halo_cats.py 677
srun --time=1 python predict_save_halo_cats.py 678
srun --time=1 python predict_save_halo_cats.py 679
srun --time=1 python predict_save_halo_cats.py 680
srun --time=1 python predict_save_halo_cats.py 681
srun --time=1 python predict_save_halo_cats.py 682
srun --time=1 python predict_save_halo_cats.py 683
srun --time=1 python predict_save_halo_cats.py 684
srun --time=1 python predict_save_halo_cats.py 685
srun --time=1 python predict_save_halo_cats.py 686
srun --time=1 python predict_save_halo_cats.py 687
srun --time=1 python predict_save_halo_cats.py 688
srun --time=1 python predict_save_halo_cats.py 689
srun --time=1 python predict_save_halo_cats.py 690
srun --time=1 python predict_save_halo_cats.py 691
srun --time=1 python predict_save_halo_cats.py 692
srun --time=1 python predict_save_halo_cats.py 693
srun --time=1 python predict_save_halo_cats.py 694
srun --time=1 python predict_save_halo_cats.py 695
srun --time=1 python predict_save_halo_cats.py 696
srun --time=1 python predict_save_halo_cats.py 697
srun --time=1 python predict_save_halo_cats.py 698
srun --time=1 python predict_save_halo_cats.py 699
srun --time=1 python predict_save_halo_cats.py 700
srun --time=1 python predict_save_halo_cats.py 701
srun --time=1 python predict_save_halo_cats.py 702
srun --time=1 python predict_save_halo_cats.py 703
srun --time=1 python predict_save_halo_cats.py 704
srun --time=1 python predict_save_halo_cats.py 705
srun --time=1 python predict_save_halo_cats.py 706
srun --time=1 python predict_save_halo_cats.py 707
srun --time=1 python predict_save_halo_cats.py 708
srun --time=1 python predict_save_halo_cats.py 709
srun --time=1 python predict_save_halo_cats.py 710
srun --time=1 python predict_save_halo_cats.py 711
srun --time=1 python predict_save_halo_cats.py 712
srun --time=1 python predict_save_halo_cats.py 713
srun --time=1 python predict_save_halo_cats.py 714
srun --time=1 python predict_save_halo_cats.py 715
srun --time=1 python predict_save_halo_cats.py 716
srun --time=1 python predict_save_halo_cats.py 717
srun --time=1 python predict_save_halo_cats.py 718
srun --time=1 python predict_save_halo_cats.py 719
srun --time=1 python predict_save_halo_cats.py 720
srun --time=1 python predict_save_halo_cats.py 721
srun --time=1 python predict_save_halo_cats.py 722
srun --time=1 python predict_save_halo_cats.py 723
srun --time=1 python predict_save_halo_cats.py 724
srun --time=1 python predict_save_halo_cats.py 725
srun --time=1 python predict_save_halo_cats.py 726
srun --time=1 python predict_save_halo_cats.py 727
srun --time=1 python predict_save_halo_cats.py 728
srun --time=1 python predict_save_halo_cats.py 729
srun --time=1 python predict_save_halo_cats.py 730
srun --time=1 python predict_save_halo_cats.py 731
srun --time=1 python predict_save_halo_cats.py 732
srun --time=1 python predict_save_halo_cats.py 733
srun --time=1 python predict_save_halo_cats.py 734
srun --time=1 python predict_save_halo_cats.py 735
srun --time=1 python predict_save_halo_cats.py 736
srun --time=1 python predict_save_halo_cats.py 737
srun --time=1 python predict_save_halo_cats.py 738
srun --time=1 python predict_save_halo_cats.py 739
srun --time=1 python predict_save_halo_cats.py 740
srun --time=1 python predict_save_halo_cats.py 741
srun --time=1 python predict_save_halo_cats.py 742
srun --time=1 python predict_save_halo_cats.py 743
srun --time=1 python predict_save_halo_cats.py 744
srun --time=1 python predict_save_halo_cats.py 745
srun --time=1 python predict_save_halo_cats.py 746
srun --time=1 python predict_save_halo_cats.py 747
srun --time=1 python predict_save_halo_cats.py 748
srun --time=1 python predict_save_halo_cats.py 749
srun --time=1 python predict_save_halo_cats.py 750
srun --time=1 python predict_save_halo_cats.py 751
srun --time=1 python predict_save_halo_cats.py 752
srun --time=1 python predict_save_halo_cats.py 753
srun --time=1 python predict_save_halo_cats.py 754
srun --time=1 python predict_save_halo_cats.py 755
srun --time=1 python predict_save_halo_cats.py 756
srun --time=1 python predict_save_halo_cats.py 757
srun --time=1 python predict_save_halo_cats.py 758
srun --time=1 python predict_save_halo_cats.py 759
srun --time=1 python predict_save_halo_cats.py 760
srun --time=1 python predict_save_halo_cats.py 761
srun --time=1 python predict_save_halo_cats.py 762
srun --time=1 python predict_save_halo_cats.py 763
srun --time=1 python predict_save_halo_cats.py 764
srun --time=1 python predict_save_halo_cats.py 765
srun --time=1 python predict_save_halo_cats.py 766
srun --time=1 python predict_save_halo_cats.py 767
srun --time=1 python predict_save_halo_cats.py 768
srun --time=1 python predict_save_halo_cats.py 769
srun --time=1 python predict_save_halo_cats.py 770
srun --time=1 python predict_save_halo_cats.py 771
srun --time=1 python predict_save_halo_cats.py 772
srun --time=1 python predict_save_halo_cats.py 773
srun --time=1 python predict_save_halo_cats.py 774
srun --time=1 python predict_save_halo_cats.py 775
srun --time=1 python predict_save_halo_cats.py 776
srun --time=1 python predict_save_halo_cats.py 777
srun --time=1 python predict_save_halo_cats.py 778
srun --time=1 python predict_save_halo_cats.py 779
srun --time=1 python predict_save_halo_cats.py 780
srun --time=1 python predict_save_halo_cats.py 781
srun --time=1 python predict_save_halo_cats.py 782
srun --time=1 python predict_save_halo_cats.py 783
srun --time=1 python predict_save_halo_cats.py 784
srun --time=1 python predict_save_halo_cats.py 785
srun --time=1 python predict_save_halo_cats.py 786
srun --time=1 python predict_save_halo_cats.py 787
srun --time=1 python predict_save_halo_cats.py 788
srun --time=1 python predict_save_halo_cats.py 789
srun --time=1 python predict_save_halo_cats.py 790
srun --time=1 python predict_save_halo_cats.py 791
srun --time=1 python predict_save_halo_cats.py 792
srun --time=1 python predict_save_halo_cats.py 793
srun --time=1 python predict_save_halo_cats.py 794
srun --time=1 python predict_save_halo_cats.py 795
srun --time=1 python predict_save_halo_cats.py 796
srun --time=1 python predict_save_halo_cats.py 797
srun --time=1 python predict_save_halo_cats.py 798
srun --time=1 python predict_save_halo_cats.py 799


echo "All done!"
